

// payment status
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_PENDING = "PAYMENT_PENDING";
export const WALLET_PAYMENT_SUCCESS = "WALLET_PAYMENT_SUCCESS";
export const PAYOUT_SUCCESS = "PAYOUT_SUCCESS";
export const PAYOUT_PENDING = "PAYOUT_PENDING";
export const PAYMENT_REFUNDED = "PAYMENT_REFUNDED";
export const PAYMENT_REFUND_FAILED = "PAYMENT_REFUND_FAILED";

// status function


export const statusCode = {
  BAD_REQUEST: "BAD_REQUEST",
  BLOCKED: "BLOCKED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  ACCESS_DENIED: "ACCESS_DENIED",
  NOT_FOUND: "NOT_FOUND",
  CREATED: "CREATED",
  ADDED: "ADDED",
  UPDATED: "UPDATED",
  DELETED: "DELETED",
  OK: "OK",
  LIMIT_EXCEED: "LIMIT_EXCEED",
};


export const payMethod = {
  WALLET: 'WALLET',
  INSTALLMENT: 'INSTALLMENT',
  WALLET_INSTALLMENT: 'WALLET_INSTALLMENT'
}